scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: 0.001
    max_y: 0.001
    max_z: 200
    min_x: -0.001
    min_y: -0.001 
    min_z: -100
    invert: true    
