// Generated by gencpp from file jet_algo/CheckGoalResponse.msg
// DO NOT EDIT!


#ifndef JET_ALGO_MESSAGE_CHECKGOALRESPONSE_H
#define JET_ALGO_MESSAGE_CHECKGOALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jet_algo
{
template <class ContainerAllocator>
struct CheckGoalResponse_
{
  typedef CheckGoalResponse_<ContainerAllocator> Type;

  CheckGoalResponse_()
    : is_applicable(false)  {
    }
  CheckGoalResponse_(const ContainerAllocator& _alloc)
    : is_applicable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_applicable_type;
  _is_applicable_type is_applicable;





  typedef boost::shared_ptr< ::jet_algo::CheckGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jet_algo::CheckGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckGoalResponse_

typedef ::jet_algo::CheckGoalResponse_<std::allocator<void> > CheckGoalResponse;

typedef boost::shared_ptr< ::jet_algo::CheckGoalResponse > CheckGoalResponsePtr;
typedef boost::shared_ptr< ::jet_algo::CheckGoalResponse const> CheckGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jet_algo::CheckGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jet_algo::CheckGoalResponse_<ContainerAllocator1> & lhs, const ::jet_algo::CheckGoalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_applicable == rhs.is_applicable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jet_algo::CheckGoalResponse_<ContainerAllocator1> & lhs, const ::jet_algo::CheckGoalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jet_algo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jet_algo::CheckGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jet_algo::CheckGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jet_algo::CheckGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49cdb8b63f4b4453767df0903ba03977";
  }

  static const char* value(const ::jet_algo::CheckGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49cdb8b63f4b4453ULL;
  static const uint64_t static_value2 = 0x767df0903ba03977ULL;
};

template<class ContainerAllocator>
struct DataType< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jet_algo/CheckGoalResponse";
  }

  static const char* value(const ::jet_algo::CheckGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_applicable\n"
"\n"
;
  }

  static const char* value(const ::jet_algo::CheckGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_applicable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jet_algo::CheckGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jet_algo::CheckGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_applicable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_applicable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JET_ALGO_MESSAGE_CHECKGOALRESPONSE_H
