// Generated by gencpp from file jet_algo/CheckGoal.msg
// DO NOT EDIT!


#ifndef JET_ALGO_MESSAGE_CHECKGOAL_H
#define JET_ALGO_MESSAGE_CHECKGOAL_H

#include <ros/service_traits.h>


#include <jet_algo/CheckGoalRequest.h>
#include <jet_algo/CheckGoalResponse.h>


namespace jet_algo
{

struct CheckGoal
{

typedef CheckGoalRequest Request;
typedef CheckGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckGoal
} // namespace jet_algo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jet_algo::CheckGoal > {
  static const char* value()
  {
    return "547d92c6b43afde2ab954b07f001fe33";
  }

  static const char* value(const ::jet_algo::CheckGoal&) { return value(); }
};

template<>
struct DataType< ::jet_algo::CheckGoal > {
  static const char* value()
  {
    return "jet_algo/CheckGoal";
  }

  static const char* value(const ::jet_algo::CheckGoal&) { return value(); }
};


// service_traits::MD5Sum< ::jet_algo::CheckGoalRequest> should match
// service_traits::MD5Sum< ::jet_algo::CheckGoal >
template<>
struct MD5Sum< ::jet_algo::CheckGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jet_algo::CheckGoal >::value();
  }
  static const char* value(const ::jet_algo::CheckGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jet_algo::CheckGoalRequest> should match
// service_traits::DataType< ::jet_algo::CheckGoal >
template<>
struct DataType< ::jet_algo::CheckGoalRequest>
{
  static const char* value()
  {
    return DataType< ::jet_algo::CheckGoal >::value();
  }
  static const char* value(const ::jet_algo::CheckGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jet_algo::CheckGoalResponse> should match
// service_traits::MD5Sum< ::jet_algo::CheckGoal >
template<>
struct MD5Sum< ::jet_algo::CheckGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jet_algo::CheckGoal >::value();
  }
  static const char* value(const ::jet_algo::CheckGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jet_algo::CheckGoalResponse> should match
// service_traits::DataType< ::jet_algo::CheckGoal >
template<>
struct DataType< ::jet_algo::CheckGoalResponse>
{
  static const char* value()
  {
    return DataType< ::jet_algo::CheckGoal >::value();
  }
  static const char* value(const ::jet_algo::CheckGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JET_ALGO_MESSAGE_CHECKGOAL_H
