// Generated by gencpp from file jet_algo/CheckGoalRequest.msg
// DO NOT EDIT!


#ifndef JET_ALGO_MESSAGE_CHECKGOALREQUEST_H
#define JET_ALGO_MESSAGE_CHECKGOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace jet_algo
{
template <class ContainerAllocator>
struct CheckGoalRequest_
{
  typedef CheckGoalRequest_<ContainerAllocator> Type;

  CheckGoalRequest_()
    : goal()  {
    }
  CheckGoalRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::jet_algo::CheckGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jet_algo::CheckGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckGoalRequest_

typedef ::jet_algo::CheckGoalRequest_<std::allocator<void> > CheckGoalRequest;

typedef boost::shared_ptr< ::jet_algo::CheckGoalRequest > CheckGoalRequestPtr;
typedef boost::shared_ptr< ::jet_algo::CheckGoalRequest const> CheckGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jet_algo::CheckGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jet_algo::CheckGoalRequest_<ContainerAllocator1> & lhs, const ::jet_algo::CheckGoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jet_algo::CheckGoalRequest_<ContainerAllocator1> & lhs, const ::jet_algo::CheckGoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jet_algo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jet_algo::CheckGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jet_algo::CheckGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jet_algo::CheckGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85ae384b155cfbcdf597bf321f1d0169";
  }

  static const char* value(const ::jet_algo::CheckGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85ae384b155cfbcdULL;
  static const uint64_t static_value2 = 0xf597bf321f1d0169ULL;
};

template<class ContainerAllocator>
struct DataType< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jet_algo/CheckGoalRequest";
  }

  static const char* value(const ::jet_algo::CheckGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped goal\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::jet_algo::CheckGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jet_algo::CheckGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jet_algo::CheckGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JET_ALGO_MESSAGE_CHECKGOALREQUEST_H
