// Generated by gencpp from file jet_algo/Frontier.msg
// DO NOT EDIT!


#ifndef JET_ALGO_MESSAGE_FRONTIER_H
#define JET_ALGO_MESSAGE_FRONTIER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace jet_algo
{
template <class ContainerAllocator>
struct Frontier_
{
  typedef Frontier_<ContainerAllocator> Type;

  Frontier_()
    : size(0)
    , centroid()  {
    }
  Frontier_(const ContainerAllocator& _alloc)
    : size(0)
    , centroid(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _size_type;
  _size_type size;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _centroid_type;
  _centroid_type centroid;





  typedef boost::shared_ptr< ::jet_algo::Frontier_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jet_algo::Frontier_<ContainerAllocator> const> ConstPtr;

}; // struct Frontier_

typedef ::jet_algo::Frontier_<std::allocator<void> > Frontier;

typedef boost::shared_ptr< ::jet_algo::Frontier > FrontierPtr;
typedef boost::shared_ptr< ::jet_algo::Frontier const> FrontierConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jet_algo::Frontier_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jet_algo::Frontier_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jet_algo::Frontier_<ContainerAllocator1> & lhs, const ::jet_algo::Frontier_<ContainerAllocator2> & rhs)
{
  return lhs.size == rhs.size &&
    lhs.centroid == rhs.centroid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jet_algo::Frontier_<ContainerAllocator1> & lhs, const ::jet_algo::Frontier_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jet_algo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jet_algo::Frontier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jet_algo::Frontier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jet_algo::Frontier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jet_algo::Frontier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jet_algo::Frontier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jet_algo::Frontier_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jet_algo::Frontier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02475197d3519817f561b4e34a7be18f";
  }

  static const char* value(const ::jet_algo::Frontier_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02475197d3519817ULL;
  static const uint64_t static_value2 = 0xf561b4e34a7be18fULL;
};

template<class ContainerAllocator>
struct DataType< ::jet_algo::Frontier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jet_algo/Frontier";
  }

  static const char* value(const ::jet_algo::Frontier_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jet_algo::Frontier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 size\n"
"geometry_msgs/Point centroid\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::jet_algo::Frontier_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jet_algo::Frontier_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.size);
      stream.next(m.centroid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Frontier_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jet_algo::Frontier_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jet_algo::Frontier_<ContainerAllocator>& v)
  {
    s << indent << "size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.size);
    s << indent << "centroid: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.centroid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JET_ALGO_MESSAGE_FRONTIER_H
