// Generated by gencpp from file jet_algo/FrontierList.msg
// DO NOT EDIT!


#ifndef JET_ALGO_MESSAGE_FRONTIERLIST_H
#define JET_ALGO_MESSAGE_FRONTIERLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jet_algo/Frontier.h>

namespace jet_algo
{
template <class ContainerAllocator>
struct FrontierList_
{
  typedef FrontierList_<ContainerAllocator> Type;

  FrontierList_()
    : frontiers()  {
    }
  FrontierList_(const ContainerAllocator& _alloc)
    : frontiers(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::jet_algo::Frontier_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::jet_algo::Frontier_<ContainerAllocator> >> _frontiers_type;
  _frontiers_type frontiers;





  typedef boost::shared_ptr< ::jet_algo::FrontierList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jet_algo::FrontierList_<ContainerAllocator> const> ConstPtr;

}; // struct FrontierList_

typedef ::jet_algo::FrontierList_<std::allocator<void> > FrontierList;

typedef boost::shared_ptr< ::jet_algo::FrontierList > FrontierListPtr;
typedef boost::shared_ptr< ::jet_algo::FrontierList const> FrontierListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jet_algo::FrontierList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jet_algo::FrontierList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jet_algo::FrontierList_<ContainerAllocator1> & lhs, const ::jet_algo::FrontierList_<ContainerAllocator2> & rhs)
{
  return lhs.frontiers == rhs.frontiers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jet_algo::FrontierList_<ContainerAllocator1> & lhs, const ::jet_algo::FrontierList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jet_algo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jet_algo::FrontierList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jet_algo::FrontierList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jet_algo::FrontierList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jet_algo::FrontierList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jet_algo::FrontierList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jet_algo::FrontierList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jet_algo::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f27a97cf07f8421b3ea35c2336a4edc";
  }

  static const char* value(const ::jet_algo::FrontierList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f27a97cf07f8421ULL;
  static const uint64_t static_value2 = 0xb3ea35c2336a4edcULL;
};

template<class ContainerAllocator>
struct DataType< ::jet_algo::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jet_algo/FrontierList";
  }

  static const char* value(const ::jet_algo::FrontierList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jet_algo::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Frontier[] frontiers\n"
"\n"
"================================================================================\n"
"MSG: jet_algo/Frontier\n"
"uint32 size\n"
"geometry_msgs/Point centroid\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::jet_algo::FrontierList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jet_algo::FrontierList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frontiers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrontierList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jet_algo::FrontierList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jet_algo::FrontierList_<ContainerAllocator>& v)
  {
    s << indent << "frontiers[]" << std::endl;
    for (size_t i = 0; i < v.frontiers.size(); ++i)
    {
      s << indent << "  frontiers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::jet_algo::Frontier_<ContainerAllocator> >::stream(s, indent + "    ", v.frontiers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JET_ALGO_MESSAGE_FRONTIERLIST_H
